#!/bin/sh
set -e +x
COPYING="$( cat <<'EOF'
Copyright 2023 tnak@nekonaq.com
License Apache 2.0: <http://www.apache.org/licenses/LICENSE-2.0>
EOF
)"
prog="${0##*/}"
run="${PT__noop:+: }"

RCSID='$Id: set-hostname,v 1.2 2024/01/18 21:13:15 nak Exp nak $'

usage() {
  cat <<EOF
Usage:
  $prog [OPTION...] [FQDN]

  システムのホスト名を設定する。
  パラメータを指定しない場合は現在のホスト名を表示する。

Options:
  -h, --help           このヘルプを表示する。
  --version            プログラムのバージョンを表示する。

Example:
  $prog vm1.example.com

EOF
}

print_version() {
  local version="$( echo "$RCSID" | awk '{ print $3, gensub(/\//, "-", "g", $4)}' )"
  if [ -z "${version# }" ]; then
    version="wip-$( date -Id -r "$0" )"
  fi
  echo "$prog $version\n$COPYING"
}

ensure_root() {
  if [ "$( id -u )" != 0 ]; then
    echo "$prog: You must be a root." >&2
    return 1
  fi
}

get_hostname() {
  cat /etc/hostname
}

hostname__() {
  local value="$1"
  if [ -z "$value" ]; then
    hostname__show
    return
  fi
  hostname__test "$value"
}

hostname__show() {
  local value="$1"
  echo "hostname: [$( get_hostname )]"
}

hostname__test() {
  local value="$1"
  [ "$value" = "$( get_hostname )" ]
}

hostname__update() {
  local value="$1"
  if ! hostname__test "$value"; then
    hostname__set "$value"
  fi
}

hostname__set() {
  local hostname="$1"
  ensure_root
  ( set -x
    ${run}hostnamectl set-hostname "$hostname"
  ) || (
    # dbus が動作していない場合の処置
    echo "$hostname" | (
      set -x
      ${run}install -o root -g root -m 644 /etc/hostname
    )
  )
}

main() {
  if [ -n "$PT__task" ]; then
    exec 2>&1
    set -- "$PT_value"

    local epp_arg='<%= $op %>'
    case "$epp_arg" in
      \<*) ;;
      *) PT_op="$epp_arg";;
    esac
  fi

  ARGS=$( getopt --name $prog --long help,version,dry-run,test --options h -- "$@" )
  if [ $? != 0 ]; then
    echo "$prog: getopt error occured: $?" >&2
    exit 2
  fi
  eval set -- "$ARGS"

  local op="${PT_op:-update}"
  while [ $# -gt 0 ]; do
    case "$1" in
      -h|--help)
        usage
        return
        ;;
      --version)
        print_version
        return
        ;;
      --test)
        op=test
        ;;
      --dry-run)
        run=': '
        ;;
      --)
        shift
        break
        ;;
    esac
    shift
  done

  local hostname="$1"
  if [ -z "$hostname" ]; then
    hostname__show
    return
  fi
  "hostname__$op" "$hostname"
}

main "$@"

# Local Variables:
# fill-column: 84
# End:
