#!/bin/sh
set -e +x
COPYING="$( cat <<'EOF'
Copyright 2023 tnak@nekonaq.com
License Apache 2.0: <http://www.apache.org/licenses/LICENSE-2.0>
EOF
)"
prog="${0##*/}"
me="$( realpath "$0" )"

RCSID='$Id$'
VAGRANT_PLUGINS="
vagrant-hostmanager
vagrant-bolt
$0.includes/vagrant-config_builder-1.3.0.2310.1.gem
"

main() {
  local plugin
  for plugin in $VAGRANT_PLUGINS "$@"; do
    ( set -x
      vagrant plugin install "$plugin"
    )
  done
}

main "$@"

# Local Variables:
# fill-column: 84
# End:
