#!/bin/sh
set -e +x
COPYING="$( cat <<'EOF'
Copyright 2024 tnak@nekonaq.com
License Apache 2.0: <http://www.apache.org/licenses/LICENSE-2.0>
EOF
)"
prog="${0##*/}"
run="${PT__noop:+: }"

RCSID='$Id$'

export ID= VERSION_ID= VERSION_CODENAME=
. /etc/os-release

GRUB_CFG_FILES="
/boot/efi/EFI/${ID}/grub.cfg
/boot/grub/grub.cfg
/boot/grub2/grub.cfg
"

usage() {
  cat <<EOF
Usage:
  $prog [OPTION...] [FQDN]

  grub 設定ファイルを更新する。
  grub-mkconfig を実行し、次のパスのうち存在するファイルをすべて更新する。

  - /boot/efi/EFI/${ID}/grub.cfg
  - /boot/grub/grub.cfg
  - /boot/grub2/grub.cfg

Options:
  -l, --list           更新の対象となるファイルを表示する。更新は行わない。
  -h, --help           このヘルプを表示する。
  --version            プログラムのバージョンを表示する。

EOF
}

print_version() {
  local version="$( echo "$RCSID" | awk '{ print $3, gensub(/\//, "-", "g", $4)}' )"
  if [ -z "${version# }" ]; then
    version="wip-$( date -Id -r "$0" )"
  fi
  echo "$prog $version\n$COPYING"
}

ensure_root() {
  if [ "$( id -u )" != 0 ]; then
    echo "$prog: You must be a root." >&2
    return 1
  fi
}

grub__list() {
  local file
  for file in $GRUB_CFG_FILES; do
    if [ -f "$file" ]; then
      echo "$file"
    fi
  done
}

grub__update() {
  ${run}ensure_root
  local grub_cfg_files="$( grub__list )"
  if [ -n "$grub_cfg_files" ]; then
    ( set -x
      ${run}grub-mkconfig |
        ${run}tee $grub_cfg_files >/dev/null
    )
  fi
}

main() {
  if [ -n "$PT__task" ]; then
    exec 2>&1

    local epp_arg='<%= $op %>'
    case "$epp_arg" in
      \<*) ;;
      *) PT_op="$epp_arg";;
    esac
  fi

  ARGS=$( getopt --name $prog --long help,version,dry-run,list --options hl -- "$@" )
  if [ $? != 0 ]; then
    echo "$prog: getopt error occured: $?" >&2
    exit 2
  fi
  eval set -- "$ARGS"

  local op="${PT_op:-update}"
  while [ $# -gt 0 ]; do
    case "$1" in
      -h|--help)
        usage
        return
        ;;
      --version)
        print_version
        return
        ;;
      --dry-run)
        run=': '
        ;;
      -l|--list)
        op=list
        ;;
      --)
        shift
        break
        ;;
    esac
    shift
  done

  "grub__$op"
}

main "$@"

# Local Variables:
# fill-column: 84
# End:
